### ISSUE TITLE
LED indicating antenna selection

### ISSUE THREAD

**Issue by roman-dvorak** [ThunderFly-aerospace/TFSIK01#13]
Bylo by docela fajn přidat na PCB LEDku, která by signalizovala použitou anténu. Z hlediska SW by to mělo jít vyřešit: https://github.com/ThunderFly-aerospace/SiK/issues/8

Znamenalo by to tedy přidat LEDku na pin P1.6

**Comment by kaklik** [comment]
Vypadá to, že požadovaná LED je na PCB přidaná, pouze není vyřena podpora uvnitř FW a dotyčná LED po zapnutí napájení stále svítí. 

![image](https://user-images.githubusercontent.com/1194177/189905999-26481558-1bdc-44e8-aa4f-524fffa61829.png)
