### ISSUE TITLE
RX/TX control

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFSIK01#15]
Vypadá to, že při návrhu modulu, došlo k odlišnosti od původního [RFSWITCH01A](https://github.com/mlab-modules/RFSWITCH01). Ten měl původně RX a TX ovládané pouze jedním pinem, který zároveň vypínal LNA (ve schéma SW1_CTRL). 

![image](https://user-images.githubusercontent.com/1194177/189907106-aec03231-5e38-433d-b863-38deec0dfa5f.png)

U nového modulu ovšem došlo k rozdělení tohoto ovládání na dva piny

![image](https://user-images.githubusercontent.com/1194177/189906766-81d15477-4be8-4996-b14d-6a31e383fe0f.png)

Důsledkem je, že nelze použít původní firmware pro pozemní stanici tak jak je, neboť ten předpokládá ovládání pouze přes jeden pin. 

Vůbec jsem nevěděl že k této změně došlo. Můžete se prosím @povik  a @ChroustJan  domluvit jak tuto situaci vyřešit?   Já bych považoval za přirozené, aby ve firmware vznikla nová definice desky TFSIK01A.

**Comment by kaklik** [comment]
Dále jsem zjistil, že nový Holybro modem předpokládá také ovládání dvěma piny, ale jsou řízeny komplementárně.

![image](https://user-images.githubusercontent.com/1194177/189925051-869e40e5-32d5-4d25-ac54-6348dc17dcc8.png)

Je tak pravděpodobné, že upstream firmware je pro řízení RX/TX dvěma piny připraven. Problematická je akorát jejich polarita, která mi pro náš případ vychází stejná u obou signálů.

**Comment by povik** [comment]
> Můžete se prosím @povik a @ChroustJan domluvit jak tuto situaci vyřešit? Já bych považoval za přirozené, aby ve firmware vznikla nová definice desky TFSIK01A.

Můžeme taky jen rozšířit/upravit definici té současné, pokud půjde. To bych zkusil prvně. Jinak ze starých emailů plyne, že to byla záměrná změna k usnadnění návrhu.

> Problematická je akorát jejich polarita, která mi pro náš případ vychází stejná u obou signálů.

Vychází mi to komplementárně i v našem případě. Totiž vůči RFSWITCH se prohodil smysl RF1 a RF2 u RX/TX přepínače. Nebo se U3 zapíná v nule?

**Comment by kaklik** [comment]
> Vychází mi to komplementárně i v našem případě. Totiž vůči RFSWITCH se prohodil smysl RF1 a RF2 u RX/TX přepínače. Nebo se U3 zapíná v nule?

U3 se zapíná v nule, viz [datasheet](https://www.qorvo.com/products/d/da007268).

**Comment by kaklik** [comment]
@povik to vyřešil a je i vyzkoušeno proti jednomu Holybro modemu z vírníku, že to funguje. Ve [firmware](https://github.com/ThunderFly-aerospace/SiK), ale chybí commit s řešením.
