### ISSUE TITLE
Last time buy of LNA IC

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TFSIK01#8]
The selected chip [SPF5189Z](https://www.qorvo.com/products/p/SPF5189Z#parameters) has End of Life announced on March 8, 2021.
The manufacturer proposes the use of [QPL9547](https://www.qorvo.com/products/p/QPL9547#parameters), which has a similar characteristic on the first look. 

The noticeable feature is Shutdown input, which allows direct control of LNA from MCU IO pin. Therefore the current LNA control logic could be significantly reduced: 

![image](https://user-images.githubusercontent.com/1194177/119550332-922c7d80-bd98-11eb-88ff-62699d81cae1.png)

To the following circuit

![image](https://user-images.githubusercontent.com/1194177/119550625-ee8f9d00-bd98-11eb-8c98-46482c96021a.png)

The unknown value is a value of resistor R4, which sets the bias point. Datasheets do not explain the possible range of values. But it is suspected, that current thought this resistor should be in the range from 65mA to 100mA. 

Resistors R3, R2, and R1 should be omitted. 

----

@ChroustJan  Dovedeš osadit i tu novou verzi?

**Comment by ChroustJan** [comment]
Ano. @kaklik takže takto má vypadat nové výsledné zapojení? 
![image](https://user-images.githubusercontent.com/9783606/119778229-89869500-bec7-11eb-8ecd-bae1f6a3b08c.png)

R4 zvoleno 3k32 po vzoru Evaluation Board – QPL9547EVB-01

**Comment by kaklik** [comment]
Na tom GPIO2 bych zachoval tu LED D5, co tam vlastně byla.   Dal bych k ní popisek RF RX, pokud bude z napájení do pinu, tak bude svítit, když je zapnuný LNA (ten je zapnutý v nule).

Jinak je to ok. .. Ta  hodnota toho R4 se asi bohužel bude muset experimentálně vyzkoušet, na to řešení teď nemám.

**Comment by ChroustJan** [comment]
Aplikován QPL9547 a přidána LED.
